[azure_openai]
AZURE_OPENAI_KEY = "2CaoyNC4H6KmrItSQWkGqylej9hsggC5j5bHQV4la8Gxw0zGf4Z8JQQJ99BBAC5T7U2XJ3w3AAABACOGwuGv"
AZURE_OPENAI_ENDPOINT = "https://chat-genai.openai.azure.com"
DEPLOYMENT_NAME = "gpt-4o"
API_VERSION = "2024-02-15-preview"
